import type { Metadata } from "next";
import { Poppins, El_Messiri } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "@/components/ResponsiveNav/ResponsiveNav";
import Footer from "@/components/Footer/Footer";
import ScrollTop from "@/components/Helper/ScrollTop";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin-ext"],
  variable: "--font-Poppins",
});

const messiri = El_Messiri({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin-ext"],
  variable: "--font-Messiri",
});

export const metadata: Metadata = {
  title: "Studio-Mp4",
  description: "Generated by using next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${messiri.variable} antialiased`}>
        <ResponsiveNav />
        {children}
        <Footer />
        <ScrollTop />
      </body>
    </html>
  );
}
